### ISSUE TITLE
Feature request: automaticaly resize image in JCE core Editor

### ISSUE THREAD

**Issue by ghost** [dgt41/imageUploaderHelper#5]
how can we use imageUploaderHelper as a plugin in jce editor ?

we want to implement image resize feature

for example then user uploads a 5Mb photo plugint automaticaly resize that photo to 200Kb ?

how to implement this feature ?

**Comment by dgrammatiko** [comment]
@Milglius this needs a bit of research, you see I don't use jce so I have to dig a bit on their codebase. Ill try to d/l and check this weekend and come back with an answer.

**Comment by ghost** [comment]
@dgrammatiko thanks for your help, it would be great to have this feature

**Comment by dgrammatiko** [comment]
@Milglius looking at their source I saw that they are using the same event names, so to make this plugin work with jce I guess all you need is to change:
https://github.com/dgrammatiko/imageUploaderHelper/blob/132b84f4b1f3da3ad71dbfd79d3435fcdc5c2972/packaging/src/uploader.php#L32-L35

to something like 
```php
		if ($context != 'com_jce.file')
		{
			return;
		}
```

If that doesnt work just upload an image and in the browser tools check the ajax request and adjust accordingly

**Comment by ghost** [comment]
but how to make it automaticaly resize every photo to 200Kb ?

**Comment by dgrammatiko** [comment]
Check my other plugin: https://github.com/ttc-freebies/plugin-responsive-images/blob/master/responsive.php Although it will not resize to certain file size it does something far more valuable: it gives you srcset for each image

**Comment by ghost** [comment]
Can you make this plugin for jce for example then user uploads a 5Mb photo plugin that automaticaly resize that photo to 200Kb or gives you srcset for each image?

**Comment by ghost** [comment]
> ```
> if ($context != 'com_jce.file')
> 		{
> 			return;
> 		}
> ```

that doesn't work 

maybe the problem is with Initial folder name ?

how to use ajax request in this case to ajust accordingly?

thank you for your help @dgrammatiko

**Comment by ghost** [comment]
Do you think yu can make this plugin ?

**Comment by ghost** [comment]
We are trying to create free plugin for jce core editor extension. Your help would be in big need.

https://github.com/Milglius/resizeonupload

@dgrammatiko  please let us know if you like what we are doing or you want to create this plugin yourself ? Please inform if we mentioned your contribution correctly, or you want us to change something or add ?

**Comment by dgrammatiko** [comment]
@Milglius sorry I'm not interested spending time to support JCE. You see for me JCE is using a really outdated code (tinyMCE v3 when there is a v5) and also I'm happy to use the core provided tinyMCE editor.

I will wish good luck on your adventure adapting this plugin to support JCE.

PS: For legal reasons, if you plan to make this plugin publicly available you need to **properly fork and mention this repo**

**Comment by ghost** [comment]
how to properly fork this repo? 

I am not interested to make this plugin available if no one participates in developing it

shame that jce using such outdated plugin I thought they use v4 or v5

what version joomla is using?

its not jce support its support of abandonned joomla users. jce has paid version not free one.

joomla 3.9.10 users do not have free image resize on upload feature

**Comment by dgrammatiko** [comment]
> joomla 3.9.10 users do not have free image resize on upload feature

That's not true, use this plugin, stop using JCE and you'll be fine

**Comment by ghost** [comment]
I would like to stop using jce but its the only plugin with whom users only see own images not other users images then they upload image.

so best option to use this plugin and jce, but the problem is jce do not let this plugin to resize pictures for free

I hope you reconsider and help joomla users to enjoy your plugin using jce

I still do not know why your plugin do not work using jce, it seems like your plugin cant start to resize pictures and I do not know why

this feature is in big need but we do not have money to buy it now

I am very sad now that you say that you are not interested to see how your plugin works with jce.
